default: &default
  adapter: postgresql
  encoding: unicode
  url: postgres://postgres:postgres@db:5432/database
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
