name: tests
run-name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: actions/setup-ruby@v2
        with:
          ruby-version: 2.7.1

      - name: Install dependencies
        run: |
          bundle install
          yarn install

      - name: Build and test
        run: |
          docker-compose build
          docker-compose run web exec db:create
          docker-compose run web bundle exec rake test
